import Header from "../components/Header";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import "./globals.css";
import { Inter, Open_Sans } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const sans = Open_Sans({ subsets: ["latin"], weight: ["400", "600"] });

export const metadata = {
  title: "Rainbow Academic Homes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <Header />
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
